### ISSUE TITLE
`ambiguous call` error when trying to pack an array of characters

### ISSUE THREAD

**Issue by dawkot** [jangko/msgpack4nim#11]
```nim
import msgpack4nim, streams

var xs: array[160, char]
newStringStream().pack(xs)
```

> Error: ambiguous call; both msgpack4nim.pack_type(s: Stream, val: openarray[T])[declared in C:\Users\kamil\.ni
> mble\pkgs\msgpack4nim-0.1.7\msgpack4nim.nim(631, 5)] and msgpack4nim.pack_type(s: Stream, val: cstring)[declared in C:\Users\kamil\.nimble\pkgs\msgpack4nim-0.1.7\msgpack4nim.nim(1097
> , 5)] match for: (Stream, array[0..159, char])

**Comment by jangko** [comment]
which nim version do you use?
I use nim 0.17.3, and have no problem

**Comment by dawkot** [comment]
I used 1.17.2 stable. With devel I have no problem as well, so I guess there's nothing to fix.
