### ISSUE TITLE
JsonNode interface

### ISSUE THREAD

**Issue by FedericoCeratto** [jangko/msgpack4nim#16]
Hello,
packing from and unpacking to JsonNode would be really handy.

**Comment by jangko** [comment]
looks like a good idea, however i need to remind myself with these

These are the differences in what objects are representable in each format:

 *  JSON keys must be strings. MessagePack keys can be any type, including maps and arrays.

 *  JSON supports "bignums", i.e. integers of any size. MessagePack integers must fit within a 64-bit signed or unsigned integer.

 *  JSON real numbers are specified in decimal scientific notation and can have arbitrary precision. MessagePack real numbers are in IEEE 754 standard 32-bit or 64-bit binary.

 *  MessagePack supports binary and extension type objects. JSON does not support binary data. Binary data is often encoded into a base64 string to be embedded into a JSON document.

 *  A JSON document can be encoded in UTF-8, UTF-16 or UTF-32, and the entire document must be in the same encoding. MessagePack strings are required to be UTF-8, although this is not enforced by many encoding/decoding libraries.

perhaps I need to implement both strict and relaxed mode converter, what do you think?

**Comment by FedericoCeratto** [comment]
For many common uses supporting the shared subset and/or doing relaxed conversions would do.
Creating JSON objects using *% and then pack them would be very handy. Unpacking msgpack into a JsonNode allows handling dynamic structures.

**Comment by FedericoCeratto** [comment]
Thanks! 🍰
