### ISSUE TITLE
objects and maps

### ISSUE THREAD

**Issue by yglukhov** [jangko/msgpack4nim#19]
`-d:msgpack_obj_to_map` is not an option for libraries which are using `msgpack4nim`. Can we establish a stricter correspondence between objects/tuples/maps/arrays and remove the possibility to tweak it by `-d` flag? Currently there's no way of producing or reading a map without the flag.

One option would be to support JsonNode for `pack/unpack`.
Another option would be to make objects correspond to maps, and tuples correspond to lists.

**Comment by yglukhov** [comment]
Yes, but the thing is, the high level api is really useful, and I would like to stick to that. Could another option be to turn `-d:msgpack_obj_to_map` into a runtime flag of `MsgStream`?

**Comment by jangko** [comment]
that would be possible

**Comment by yglukhov** [comment]
Thank you!
