### ISSUE TITLE
fails on object variants

### ISSUE THREAD

**Issue by leemorgan-mobile** [jangko/msgpack4nim#2]
msgpack.nim(505, 6) Error: attempting to call undeclared routine: 'pack_imp_int8'

nim 0.11.3 nimble 0.6.0
...

type
  NodeKind = enum  # the different node types
    nkInt,          #a leaf with an integer value
    nkFloat,        #a leaf with a float value
    nkString,       #a leaf with a string value
    nkAdd,          #an addition
    nkSub,          #a subtraction
    nkIf            #an if statement
  Node = ref NodeObj
  NodeObj = object
    case kind: NodeKind  # the ``kind`` field is the discriminator
    of nkInt: intVal: int
    of nkFloat: floatVal: float
    of nkString: strVal: string
    of nkAdd, nkSub:
      leftOp, rightOp: Node
    of nkIf:
      condition, thenPart, elsePart: Node
    
var
  aUnion = Node(kind:nkInt, intVal:22)

var file = newFileStream("msg.pack", fmReadWrite)

file.pack(aUnion)

**Comment by jangko** [comment]
@leemorgan-mobile: thanks for your information

**Comment by leemorgan-mobile** [comment]
No worries. Thanks for the wrapper and the fast fix!
