### ISSUE TITLE
Must use Nim 0.18.0, an official "release", not "devel"

### ISSUE THREAD

**Issue by pb-cdunn** [jangko/msgpack4nim#23]
I have a problem. There is a bug in Nim's memory allocation on `devel`, so I need to use `0.18.0` until this is solved. I think I had to switch to `devel` because of something in your new code. We need to revert `msgpack4nim` to a version that works with a *released* version of *Nim*, namely `0.18.0`. What SHA1 do you think would work?

* https://forum.nim-lang.org/t/4088

**Comment by jangko** [comment]
Hmm, git bisect? You can try any commit before nim 0.18.0 release date

**Comment by pb-cdunn** [comment]
I think made various bug-fixes for me. I'll try things before March 1 and cross my fingers.

**Comment by pb-cdunn** [comment]
Nvm. They fixed `devel`.
