### ISSUE TITLE
Custom pack_type handlers for distinct types

### ISSUE THREAD

**Issue by zevv** [jangko/msgpack4nim#29]
The current method for always falling back to the undistinct base type does not allow implementing custom packing for distinct types. For example, something like this:

```
type  
  Guid = distinct string
      
proc pack_type*[ByteStream](s: ByteStream, v: Guid) =
  s.pack_bin(len(v))
  s.write(v)
      
var b: Guid = Guid("AA")

var s = b.pack
echo s.tohex
echo s.stringify
```

I'm pretty new to Nim, and not proficient enough in macro-land, but would it be possible to check at compile time if there is a matching `pack` function for a type to use, and only fall back to the base type if not?

Thanks

**Comment by jangko** [comment]
fixed, now you can use something like this:

```Nim
import msgpack4nim, strutils

type
  Guid {.skipUndistinct.} = distinct string

proc pack_type*[ByteStream](s: ByteStream, v: Guid) =
  s.pack_bin(len(v.string))
  s.write(v.string)

var b = Guid("AA")
var s = b.pack
echo s.tohex
echo s.stringify
```

automatic check for `matching procs` is not possible right now, Nim compiler still has issue in that particular area.

**Comment by zevv** [comment]
Quoting andri lim (2018-12-10 05:43:00)
> fixed, now you can use something like this:

Sweet, thank you.

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by zevv** [comment]
What about this?

```
proc pack*[ByteStream, T](s: ByteStream, val: T) =
  when compiles(s.pack_type(val)):
    s.pack_type (val)
  else:
    s.pack_type undistinct(val)
```

This works for me, without any need for special pragmas.

**Comment by jangko** [comment]
I already tried that, it only works for simple types.
For some unknown reason, when encountered `object variant` with self reference, the compiler protest with scary error. that's why I choose to use pragma.
you can try it with `tests/test_codec.nim`

**Comment by zevv** [comment]
Fair enough, thanks!
