### ISSUE TITLE
Unpacking non-homogeneous lists

### ISSUE THREAD

**Issue by andreaferretti** [jangko/msgpack4nim#3]
I am trying to use this library to communicate with a Python client. For reasons not under my control, the client serializes some nonhomogeneous lists, such as `[1, "hello", {"a": "b"}]`.

Is there a way to use the library to deserialize this? I have been able to do this in other typed languages by unpacking into a sequence of yet-unkown types (for instance in Scala I deserialize a `Seq[Any]`), and then manually mapping by position and casting. It is not the cleanest approach, but it would be very useful for me to be able to do something like this

**Comment by jangko** [comment]
take a look at [here](https://gist.github.com/df130311ebce7e51d8d4).

to use it, first add export marker `*` to the following procs in msgpack.nim
- unpack_imp_float32
- unpack_imp_float64
- unpack_imp_uint64
- unpack_imp_int64

**Comment by andreaferretti** [comment]
Thank you! For now I have settled in using the other msgpack library, that supports this natively (I can just import it from nimble without messing with the source). Any chance you could add `msgAny` to oyur library? In general I like the approach of your library very much, but it is a little limiting that not every msgpack valid message can be deserialized

**Comment by jangko** [comment]
now, msgAny already part of msgpack4nim.

**Comment by andreaferretti** [comment]
Great, thank you!!
