### ISSUE TITLE
Unable to create helper proc

### ISSUE THREAD

**Issue by renatotoyama** [jangko/msgpack4nim#43]
Hi, I've been trying to create a simple proc that uses MSGPACK_OBJ_TO_MAP as the default, much like the current implementation of pack. However, it seems that creating this helper proc and importing it from somewhere else makes it fail with `undeclared identifier: 'pack_type'`.

Here's a minimal example:

```
file:util.nim

import msgpack4nim

proc mapPack*[T](val: T): string =
  var s = MsgStream.init(sizeof(T), MSGPACK_OBJ_TO_MAP)
  s.pack(val)
  return s.data

when isMainModule:
  echo mapPack("s")
```

```
file: main.nim

import util

echo mapPack("s")
```

If run `nim c -r util.nim`, it works. But when running `nim c -r main.nim`, it complains that `pack_type` is undeclared when used in `undistinct_pack`.

I tried replicating it with simple template, but my skills with macro/template is still too green to understand why this is happening, so I wasn't able to create a minimal examples without msgpack.

Any insights?

**Comment by jangko** [comment]
many has fall into this template/generics trap.
you can use mixin, but probably the easiest is adding `export msgpack4nim` to your util.nim

or `import msgpack4nim` in your main.nim

```Nim

import msgpack4nim
export msgpack4nim

proc mapPack*[T](val: T): string =
  var s = MsgStream.init(sizeof(T), MSGPACK_OBJ_TO_MAP)
  s.pack(val)
  return s.data

when isMainModule:
  echo mapPack("s")
```

template and generics are instantiated at callsite iirc. they are not like ordinary procs.
often at callsite, they don't have correct modules imported like in declaration site.

**Comment by renatotoyama** [comment]
Hm, that makes it very hard to debug/use templates/generics, since I have to understand everything that the library is using or imported and replicate everything, or if it's not exported, replicate it in my code. Not very user-friendly nor scalable.

Anyway, this does fix it, but I wasn't able to find much info on mixin, except the brief part about symbol lookups in the manual. From what I understood, it feels like `bind` is what I'm looking for, since it "binds" the identified at the moment of the generics definition, thus in `util.nim`, which SHOULD have the pack_type from `import msgpack4nim`. But alas, it was not so simple again. It complains that `bind pack_type` is an invalid expression.

I'll close this issue as this is not really a msgpack4nim problem, and more on how Nim itself works. Really liked the language, but the gotchas and all the in-depth knowledge of  how Nim is implemented/C works that is needed to understand these gotchas is really tiring me out.

Thanks.
