### ISSUE TITLE
Defining pack_type and unpack_type for templated type does not call the specialized version

### ISSUE THREAD

**Issue by Clonkk** [jangko/msgpack4nim#49]
If I want to do the following :
 `proc pack_type*[ByteStream](s: ByteStream, x: Tensor[int64])= #...`
 `proc pack_type*[ByteStream](s: ByteStream, x: Tensor[int64])= #...`

I would like to be able to do the following : 
 `proc pack_type*[ByteStream, T: SomeFloat|SomeInteger](s: ByteStream, x: Tensor[T])= #...`

But the specialized version I define is not called when I use pack(...). Same issue with unpack

**Comment by jangko** [comment]
you can always use the low level functions of msgpack if the high level api doesn't work for you.

**Comment by Clonkk** [comment]
It actually does work and I'm just dumb.
