### ISSUE TITLE
unpack_enum_proxy error

### ISSUE THREAD

**Issue by FedericoCeratto** [jangko/msgpack4nim#5]
Hello and thanks for developing msgpack4nim
While compiling code that packs an object containing an enum I got:

.nimble/pkgs/msgpack4nim-0.1.6/msgpack.nim(1006, 14) Error: attempting to call undeclared routine: 'unpack_enum_proxy'

line 1006 reads as:
`n` = s.unpack_enum_proxy(`n`)  

Sounds related to #4

**Comment by jangko** [comment]
could you please provide sample code, because i cannot reproduce the error with simple example like this:

```nimrod
type
  GUN = enum
    PISTOL
    RIFLE
    MUSKET
    SMG
    SHOTGUN

  MilMan = object
    weapon: GUN

var a, b: MilMan
a.weapon = SMG
  
var buf = pack(a)
buf.unpack(b)
echo a.weapon
echo b.weapon
echo buf
doAssert(a.weapon == b.weapon)
```
