### ISSUE TITLE
[Question] Reading from a file

### ISSUE THREAD

**Issue by mantielero** [jangko/msgpack4nim#50]
I have some data stored as msgpack file in python. The file contains more than 250columns.

In order to read the file, do I need to create a type that holds the data? Is there a workaround for that? I mean, something that creates that type definition from the file structure.

**Comment by jangko** [comment]
```Nim
var s = newFileStream("somefile.m", fmRead)
var x = s.toAny()
```

it will create a dynamic msgpack structure in memory.
then use msgpack2any API to interrogate the content as you wish.

**Comment by jangko** [comment]
> something that creates that type definition from the file structure

code generation? no
