### ISSUE TITLE
Add the implementation to the msgpack website

### ISSUE THREAD

**Issue by Yardanico** [jangko/msgpack4nim#54]
It would be really nice to have. See the description on how to do it at https://github.com/msgpack/website/blob/master/README.md#how-to-list-up-your-project-on-msgpackorg

**Comment by Yardanico** [comment]
See e.g. how https://github.com/akiradeveloper/msgpack-nim does it in the github description (but the library itself is meh, yours is much more "royale" nim :P)

**Comment by jangko** [comment]
it has been there since the inception of `msgpack4nim`. the position of list's item is not fixed, but rather randomized. and it also not grouped by language nor sorted in any order. sometimes I also cannot find msgpack4nim easily in that website

**Comment by Yardanico** [comment]
Oh, I'm really sorry then :)
