### ISSUE TITLE
Can't use `pack` from inside a template in another module without import msgpack4nim

### ISSUE THREAD

**Issue by dawkot** [jangko/msgpack4nim#57]
### Example
y.nim
```nim
import msgpack4nim

template f* =
  discard pack(1)
```
x.nim
```nim
import y 

f()
```

### Output
```
/home/user/programming/nim/x.nim(3, 2) template/generic instantiation of `f` from here
/home/user/programming/nim/y.nim(4, 15) template/generic instantiation of `pack` from here
/home/user/.nimble/pkgs/msgpack4nim-#head/msgpack4nim.nim(1207, 4) template/generic instantiation of `pack` from here
/home/user/.nimble/pkgs/msgpack4nim-#head/msgpack4nim.nim(1202, 79) template/generic instantiation of `undistinct_pack` from here
/home/user/.nimble/pkgs/msgpack4nim-#head/msgpack4nim.nim(174, 37) Error: undeclared identifier: 'pack_type'
```

**Comment by jangko** [comment]
This is a well known problem with nim's macros/generics/template. Instantiation of generics or macro expansion happened at callsite. At callsite, the current scope don't possess all required symbols. And for optimization reason, generics instance are cached. But under some circumstances such as your example, it reveals the flaw in the generics cache implementation. The generics cache sometimes confused which scope it should use.

msgpack4nim itself relies heavily on generics and templates and some macro magic.

a usual approaches to your problem:

1. export `msgpack4nim` from `y` module, or
2. force callsite instantiation in `y` module via non-generics proc/func.

```
import msgpack4nim

func doSomething(): string {.inline.} =  
  pack(1)

template f* =
  discard doSomething()
```

**Comment by dawkot** [comment]
Thanks for an in-depth response. If it's a well known bug, then I'm assuming it has an issue in the Nim repo so I won't move it there.

**Comment by Yardanico** [comment]
FWIW you can just use bind here
