### ISSUE TITLE
nimble install doesn't seem to work

### ISSUE THREAD

**Issue by guzba** [jangko/msgpack4nim#6]
Hi! Was about to play around with this but I've run into this bump in the road:

nimble install msgpack4nim

Downloading https://github.com/jangko/msgpack4nim using git
       Tip: 1 messages have been suppressed, use --verbose to show them.
     Error: Traceback (most recent call last)
        ... nimble.nim(1073)         nimble
        ... nimble.nim(999)          doAction
        ... nimble.nim(606)          install
        ... nimble.nim(570)          downloadPkg
        ... download.nim(199)        doDownload
        ... download.nim(165)        verifyClone
        ... packageparser.nim(325)   getPkgInfo
        ... packageparser.nim(313)   getPkgInfoFromFile
        ... packageparser.nim(307)   readPackageInfo
        ... packageparser.nim(125)   validatePackageInfo
        ... packageparser.nim(28)    raiseNewValidationError
        ... The .nimble file name must match name specified inside /tmp/nimble_53350/githubcom_jangkomsgpack4nim/msgpack.nimble

**Comment by jangko** [comment]
fixed

**Comment by guzba** [comment]
Confirmed, nice quick fix.
