### ISSUE TITLE
Make MsgStream.writeData public, please

### ISSUE THREAD

**Issue by snej** [jangko/msgpack4nim#69]
Unlike the regular Stream type, MsgStream does not have a public writeData method, so I/O functions like `pack_type` using a generic `[ByteStream]` will fail to compile when `ByteStream` is `MsgStream`.

There’s no efficient workaround for writing a buffer of binary data. The alternatives are to copy the buffer to a string first and call write(string), or to write the individual bytes as write(byte). The first allocates memory and the second is quite slow.

The generic `write(MsgStream, T)` seemed like it would work, but if I call it with a `seq[byte]` it ends up writing the _pointer_ as 8 or 4 bytes, which is of course garbage.

Simply making the writeData method (at msgpack4nim.nim:69) public would resolve the problem.

(I’m not sure why MsgStream is an independent type and not an `object of Stream`? Inheriting from Stream would fix API incompatibilities and make your code smaller.)

**Comment by jangko** [comment]
I welcome PR and some test cases.

**Comment by jangko** [comment]
fixed by #71
